### ISSUE TITLE
Linux known events

### ISSUE THREAD

**Issue by achan-petpartners** [falood/file_system#10]
I am trying to use this dependency to notify when a file is created in linux.  When I ran the Exsfwatch.known_events, only [:renamed, :closed, :modified, :isdir, :undefined] gets returned. It doesn't match what the inofitywait event list.  The one i care the most is :create and not there too.  Am i missing something?

Thank you!

Ada

**Comment by falood** [comment]
That's feature of new version `fs`, I'll upgrade as soon as possible!
Thank you for reminding!

**Comment by achan-petpartners** [comment]
Thank you!

Ada Chan

**Comment by falood** [comment]
Just released v0.3.0 🙂
