### ISSUE TITLE
Adding ExFSWatch to another Elixir App

### ISSUE THREAD

**Issue by puruzio** [falood/file_system#14]
Thanks for creating ExFSWatch. It works great.
I could make it work on its own in `iex`.

Can you provide some guideline on how to add it to an existing Elixir app?
I thought it would be as simple as adding a line `supervisor(Monitor, [])` to the `children` list in my MyProject.ex, but it gave me `Monitor.start_link/0 is undefined` error.

Another question is.. I noticed there are multiple callbacks issued for a single modification of a file in the folder that's being watched. (which looks like the following) What's the reason for this behavior?

iex >> {"/folder/file1.txt", [:created]}
iex >> {"/folder/file1.txt", [:modified]}
iex >> {"/folder/file1.txt", [:modified]}
iex >> {"/folder/file1.txt", [:modified]}

**Comment by falood** [comment]
Thank you for using exfswatch ❤️ 

for the first question, the monitor has it's own supervisor, it's a child of [ExFSWatch.Supervisor](https://github.com/falood/exfswatch/blob/master/lib/exfswatch/supervisor.ex), so you don't need to add it to your own supervisor tree, just run `Monitor.start()`. If you have special reason to make it a child of your own supervisor, leave me a line and I'll try to add a `child_spec` method for it.

for the second question, `exfswatch` is a wrapper of https://github.com/synrc/fs which decide the event details. But I guess you modified the file with `vim` or other editor which trigger several times, try to use `touch` to create a file and use `echo 'hello' >> file1.txt` to modify a file, maybe you will get what you want.

**Comment by puruzio** [comment]
Thanks for your prompt response.

The reason I wanted to put in my own supervisor tree is because that's an easy way (I know of, anyway) to include it in my Phoenix project. I am trying to monitor changes of some files and show them on the users' browser via Phoenix Channel. I'm sure there are other (probably better) approaches (that I'll be happy to learn more about).

Thanks!

**Comment by falood** [comment]
added `child_spec` method and released `v0.3.1` for you ❤️ 
add `YourMonitorModule.child_spec()` to your supervisor tree like this to use it:
```
    children = [
      Monitor.child_spec(),
      ... # your other workers or supervisors
    ]
```

**Comment by puruzio** [comment]
Wow, you are awesome. Thank you!

**Comment by puruzio** [comment]
Hi, Xiangrong,

Hope you are doing well.

I'm trying your new package file_system. Thanks for well maintaining this
package.

I update my Watch module to follow the GenServer example shown in ReadMe,
and included it in the supervision tree as a child like this.

MyApp.Monitor.child_spec(dirs: ["c:\folder"])

and in mix.exs, added

applications: [:file_system]

However, the callback function defined in the Monitor genserver's
handle_info doesn't seem to run as the file changes.

I noticed that the watcher_id assigned to my Monitor in genserver init
function doesn't appear in erlang :observer.

Can you please tell me what I'm doing wrong?

Thanks in advance.

Jason

**Comment by falood** [comment]
Hi @puruzio 
with the new `file_system`, I removed module based API, so you have to modify you code to use functional API, there won't be too many codes added, check the readme for the demo 🙂

**Comment by puruzio** [comment]
Thanks for your response. I'm not exactly sure what you mean by module based API or functional API. Is this way of adding the module to the supervision tree not right?  
 `MyApp.Monitor.child_spec(dirs: ["c:\folder"])`  If not, then what's the right way?

**Comment by falood** [comment]
sorry, let me explain more.
For the `exfswatch` , you use it with `use ExFSWatch, dirs: ["MY_DIR"]` in a module, this make the module a monitor, and that's what I mean `module based API`.
But with the new `file_system`, I removed this DSL, we can only use it as a general Elixir module, to start a process, and subscribe the process like this .
```
{:ok, pid} = FileSystem.start_link(dirs: ["/path/to/some/files"])
FileSystem.subscribe(pid)
```
And then, the process you run `FileSystem.subscribe` will receive the file events, that's the only way to use `file_system`, and that's what I mean functional API.

So for now, if you want a standalone process for file system monitor processing, you have to defined it yourself, and mount it to supervisor tree manually.

[here](https://github.com/falood/file_system#example-with-genserver) is the example to run it as a standalone GenServer process, and you can run `Watcher.start_link(dirs: ["PATH"])` to start the gen_server, if you want to add it to an exists supervisor tree, you should define the `child_spec` function yourself.

Is my explain clear enough?
If you are using it for an opensource project, I can help to do the migration from `exfswatch` to `file_system`.
Feel free to leave your question again if you still have question or suggestion. 🙂

**Comment by puruzio** [comment]
Attached is how I coded it. There is no error, but file changes are not triggering `handle_info`. If you can tell me what I'm doing wrong, it will be very helpful. Thanks.

[puruzio.zip](https://github.com/falood/file_system/files/1220295/puruzio.zip)

**Comment by falood** [comment]
with your current code, just add one line ` FinReporting.Monitor.start_link(dirs: ["q:/data/mls_alltrans"])` to the `start/2` function your `fin_reporting.ex` file, like this: 
```
  def start(_type, _args) do
    FinReporting.Monitor.start_link(dirs: ["q:/data/mls_alltrans"])
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
    YOUR ORIGINAL CODE
```

**Comment by puruzio** [comment]
in the children list, remove the `Monitor.child_spec(dirs: ["...."])` line? Otherwise, the app seems to start two watcher processes.

Regardless of whether this line is removed or not, however, file changes under the specified folder are still not triggering handle_info. Any idea why?

**Comment by falood** [comment]
Oh yes, this line should be removed.
It seems you run the code under windows, but I don't have a windows device to run it locally.
You can check such points:
1. whether the system monitor process alive. The name of exec file should be `inotifywait.exe`.
2. whether the EVM monitor process alive, the watcher_pid should be `{:ok, watcher_pid} = FileSystem.start_link(args)`, print the `watcher_pid` and check it with `observer` or other tools.
3. whether the EVM handler process alive. Check the pid within the result of `FinReporting.Monitor.start_link`, `observer` also works for it.

**Comment by puruzio** [comment]
https://github.com/thekid/inotify-win/

is this the inotifywait.exe you are referring to? if so, I should have it
running in the background?

**Comment by falood** [comment]
I checked the code, it is, but I find it from https://github.com/synrc/fs/tree/master/priv .
I change nothing, just use the binary file directly.

You don't need to run it manually, `file_system` will run it automatic. I mean you should check whether the system process is alive to check whether it's run successfully by `file_system`.

**Comment by puruzio** [comment]
Assuming the system process is supposed to appear in the Windows task manager, I checked 
 under Processes tab and Services tab but can't seem to find inotifywait.exe.(or something similar) The watcher_pid does appear in :observer. Am I missing something? Thanks.

![screen shot 2017-08-13 at 7 26 24 am](https://user-images.githubusercontent.com/1150766/29250555-13afcf9c-7ff9-11e7-8e07-b9ddab2bada1.png)
![screen shot 2017-08-13 at 7 23 31 am](https://user-images.githubusercontent.com/1150766/29250557-13b44ba8-7ff9-11e7-8a8b-55b85ad2c0b4.png)
![screen shot 2017-08-13 at 7 22 28 am](https://user-images.githubusercontent.com/1150766/29250556-13b14890-7ff9-11e7-93a2-659a197497d3.png)

**Comment by puruzio** [comment]
Sorry to be a pest, but if you can take a look at the screenshots I
included here (https://github.com/falood/file_system/issues/14) I will
really appreciate it. In the meantime, I tried to go back to exfswatch
0.3.1 (which used to work fine), but I'm having the same issue there. File
changes are not being picked up by exfswatch. I wonder if this somehow has
something to do with the Elixir 1.5.1/Erlang 20 upgrade.

Thanks!

**Comment by falood** [comment]
I got a windows device today, but it's hard for me to use it for elixir development.
Give me 2 more days to test and debug 🙂

**Comment by puruzio** [comment]
Wow, you are awesome!

**Comment by falood** [comment]
@puruzio finally I run it successfully on my windows device, with file_system 0.1.5/elixir 1.5.1/erlang 20/windows 10 64bit, and everything works well.
Can you go to the `priv` dir of file_system package, and run `inotifywait.exe -r -m YOUR_PATH` directly? Check whether the command line  `inotifywait` works well

**Comment by puruzio** [comment]
Running that command directly, it works as expected (see screenshot) in the
terminal.

Within the Elixir app, though, file changes still don't seem to trigger
handle_info in FinReporting.Monitor. I also tried to run it in IEx (see 2nd image), and made
changes to the file in the path, but it created no output in IEx (maybe it
isn't supposed to).

Is there anything else you want me to try? Thanks.

![screen shot 2017-08-15 at 5 02 05 am](https://user-images.githubusercontent.com/1150766/29315247-f9eaebbc-8176-11e7-877a-cd0dafb7cea6.png)

**Comment by puruzio** [comment]
I tried another path on the local hard drive (on the server), and it
WORKS!!!

So the issue has to do with the fact that q: drive is mapped to a shared
network folder. is this what you would expect?

What's odd is that exfswatch used to work fine with this exact network shared folder, but for some reason, it's not working anymore. (after Erlang/Elixir upgrade, maybe?)

**Comment by falood** [comment]
I have no idea, you also run it successfully with the command line `inotifywait.exe`, and the `file_system` should works when the command line works

**Comment by puruzio** [comment]
Is there a way you can test with folders on a shared network folder (as
opposed to local drive)? That way we can rule out the last (unlikely)
possibility that Elixir is having issues with shared network file paths,
rather than inotifywait.exe.

**Comment by falood** [comment]
what protocol you used for the network folder? samba, nfs or anything else?

**Comment by puruzio** [comment]
Samba (SMB). Thanks.

**Comment by falood** [comment]
@puruzio I tested file_system via smb, I can catch the `create`, `modify` and `delete` event, but I can't catch `rename`.
I don't know how smb works, maybe for now, the best way to do it is runing file_system on the server with original data.

**Comment by puruzio** [comment]
Thank you for the update. Really appreciate it.

**Comment by falood** [comment]
Do you think we can close this ticket now?

**Comment by puruzio** [comment]
Sure. thanks
