### ISSUE TITLE
listener_extra_args is put at the wrong place when forming args for inotifywait

### ISSUE THREAD

**Issue by yjin77** [falood/file_system#15]
In worker.ex, start_port() for inotifywait has this code:

    args = [ listener_extra_args, '-c', 'inotifywait $0 $@ & PID=$!; read a; kill $PID',
                 '-m', '-e', 'close_write', '-e', 'moved_to', '-e', 'create', '-e',
                 'delete_self', '-e', 'delete', '-r' | path
    ]

listener_extra_args is fed to /bin/sh, instead of inotifywait. It should be placed after '-r'., like this:

    args = [ '-c', 'inotifywait $0 $@ & PID=$!; read a; kill $PID',
             '-m', '-e', 'close_write', '-e', 'moved_to', '-e', 'create', '-e',      
             'delete_self', '-e', 'delete', '-r', listener_extra_args | path    
           ]

The current implementation will cause the following error on display:

/bin/sh: : No such file or directory

**Comment by falood** [comment]
Thanks! this issue helped me to resolve another one ❤️

**Comment by ybycode** [comment]
The current InotifyWait backend still has the issue, the `listener_extra_args` is fed to the shell, to to the inotifywait command. Here's a PR: #20.
Thanks!
