### ISSUE TITLE
Could not compile dependency :fs error

### ISSUE THREAD

**Issue by jmcaffee** [falood/file_system#17]
fs has received a bug fix that resolves this issue: https://github.com/synrc/fs/issues/40

**Comment by falood** [comment]
Will release new version when new `fs` released.
hex don't allow `github depends` now, If you have to it now, try `{:fs, github: "synrc/fs", override: true}` in your own repo.
Thank you ❤️

**Comment by felipesere** [comment]
@falood `fs` has released a new version `3.4.0` https://hex.pm/packages/fs

**Comment by falood** [comment]
@felipesere I tried to upgrade, but got some errors, maybe it will take me some time to fix it, thank you for reminding.

**Comment by felipesere** [comment]
I tried it with `override: true` but I got issues with the fsevent backend.

**Comment by falood** [comment]
@felipesere I packaged `fs` in and released a new version v0.4.0, hope it's helpful.
@pguillory FYI, to keep consistent with `fs`, I rename some event for `inotify_waite` backend, such as `create` to `created`, remove `delete_self`, maybe you should update your project if you do a upgrade.
