### ISSUE TITLE
Failed to start the release

### ISSUE THREAD

**Issue by darkbaby123** [falood/file_system#19]
I use exfswatch in a Phoenix 1.2 application. Everything works fine until I build a release (using distillery) and deploy to the server. The release fails to start, the error message is like below:

```shell
$ ./bin/my_app console

Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]


=INFO REPORT==== 20-Apr-2017::16:12:21 ===
    application: plug
    exited: {bad_return,
                {{'Elixir.Plug',start,[normal,[]]},
                 {'EXIT',
                     {noproc,
                         {gen_event,call,
                             ['Elixir.Logger','Elixir.Logger.Config',
                              {add_translator,
                                  {'Elixir.Plug.Adapters.Translator',
                                      translate}}]}}}}}
    type: permanent
{"Kernel pid terminated",application_controller,"{application_start_failure,plug,{bad_return,{{'Elixir.Plug',start,[normal,[]]},{'EXIT',{noproc,{gen_event,call,['Elixir.Logger','Elixir.Logger.Config',{add_translator,{'Elixir.Plug.Adapters.Translator',translate}}]}}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,plug,{bad_return,{{'Elixir.Plug',start,[normal,[]]},{'EXIT',{noproc,{gen_event,call,['Elixir.Logger','Elixir.Logger.Config',{

Crash dump is being written to: erl_crash.dump...done
```

I reduced my code to only include exfswatch in `application` and `deps` in mix.exs. The error still happened. I guess it's because logger config but my Phoenix app already has them. Not sure what the real reason is.

**Comment by falood** [comment]
I'm sorry maybe I need more information for this error, could you please show me your `mix.exs` file?

**Comment by darkbaby123** [comment]
Sorry for the delay response, so busy these days. For simplicity I tested on a new Phoenix 1.2 project and the issue still happened. You can get the repo [here](https://github.com/darkbaby123/exfswatch_demo). Just run `mix release` then run the release like `_build/dev/rel/exfswatch_demo/bin/exfswatch_demo console` and you'll see the exception.

Here's the whole steps about how the project is created and tested:
1. Generate the project with `mix phoenix.new exfswatch_demo --no-ecto --no-brunch --no-html`
1. Add `distillery` to the `mix.exs`
1. Run `mix deps.get` and `mix compile` to enable the release tasks
1. Use `mix release.init` to generate a basic release config
1. Run `mix release` to generate a release
1. Run `_build/dev/rel/exfswatch_demo/bin/exfswatch_demo console`, see exception here

**Comment by darkbaby123** [comment]
BTW It works on a pure mix project (without any logger config). Just fail in a phoenix project.

**Comment by jwazne** [comment]
Hello,

I've exactly the same behaviour and same error as @darkbaby123 using exrm release.
Here's my mix.exs : 

def application do
    [mod: {Dexyde, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, ...
                    **:exfswatch**,
                    ...]]
  end

defp deps do
    [{:phoenix, "~ > 1.2.1"},
     {:phoenix_pubsub, "~ > 1.0"},
     {:phoenix_ecto, "~ > 3.0"},
     {:postgrex, ">= 0.0.0"},
      ...
     {:cf, "~ > 0.2.2"},
     {:exrm, "~ > 1.0"},
     {:relx, "~ > 3.22"},
     {:erlware_commons, "~ > 1.0"},
     **{:exfswatch, "~ > 0.4.1"}**]
  end

After building the release and running _**rel/myapp/bin/myapp console**_, I get the following error:

-----------
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

=INFO REPORT==== 11-May-2017::18:47:30 ===
    application: plug
    exited: {bad_return,
                {{'Elixir.Plug',start,[normal,[]]},
                 {'EXIT',
                     {noproc,
                         {gen_event,call,
                             ['Elixir.Logger','Elixir.Logger.Config',
                              {add_translator,
                                  {'Elixir.Plug.Adapters.Translator',
                                      translate}}]}}}}}
    type: permanent
{"Kernel pid terminated",application_controller,"{application_start_failure,plug,{bad_return,{{'Elixir.Plug',start,[normal,[]]},{'EXIT',{noproc,{gen_event,call,['Elixir.Logger','Elixir.Logger.Config',{add_translator,{'Elixir.Plug.Adapters.Translator',translate}}]}}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,plug,{bad_return,{{'Elixir.Plug',start,[normal,[]]},{'EXIT',{noproc,{gen_event,call,['Elixir.Logger','Elixir.Logger.Config',{

Crash dump is being written to: erl_crash.dump...done
-----------

As soon as I remove exfswatch from both application and deps, I can start a console with the release.

Any help would be much appreciate.

Many thanks 

Regards,
Julien

**Comment by falood** [comment]
OMG! I think I found the bug, it's a stupid error, I put `:logger` in `included_applications`, it should be in `applications`. have release v0.4.2.
