### ISSUE TITLE
Starting exfswatch with dynamic path at runtime

### ISSUE THREAD

**Issue by Nicd** [falood/file_system#21]
Maybe I'm missing something, but I can only see an example of writing a module that has the `dirs` option set at compile time. Is it possible to start a new watcher with a custom path at runtime? I would need to start and stop watchers when needed.

I'm currently using `fs` but looking into other more Elixir friendly options.

**Comment by falood** [comment]
sorry, exfswatch don't have such feature for now, will do it when I have time 🙂 
Thank you.

**Comment by falood** [comment]
check https://github.com/falood/file_system#subscription-api please
