### ISSUE TITLE
Always crashes with (EXIT) no process

### ISSUE THREAD

**Issue by leifg** [falood/file_system#3]
Everytime I try to run my monitor (the one from the README) I immediately get the following error:

``` elixir
Monitor.start
** (exit) exited in: GenServer.call(ExFSWatch.Supervisor, {:start_child, [Excellent.Monitor]}, :infinity)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:356: GenServer.call/3
```

**Comment by falood** [comment]
You should add `:exfswatch` to `:applications` within `mix.exs` like this:
https://github.com/falood/exsync/blob/master/mix.exs#L18

**Comment by leifg** [comment]
Thanks, that helped
