### ISSUE TITLE
Backends should stop on EXIT

### ISSUE THREAD

**Issue by josevalim** [falood/file_system#38]
The backends have this code:

```elixir
  def handle_info({:EXIT, port, _reason}, %{port: port}=state) do
    send(state.worker_pid, {:backend_file_event, self(), :stop})
    {:noreply, state}
  end
```

Shouldn't the return be `{:stop, :normal, state}`? Otherwise the backend will continue running even if they have no port? Or is this intentional?

**Comment by falood** [comment]
It's a bug, should return `{:stop, :normal, state}`, will fix it soon.

**Comment by falood** [comment]
fixed via https://github.com/falood/file_system/commit/d280e263e33a7930dacb451f07a2b90a813324c2
