### ISSUE TITLE
Zombie processes in Debian with inotifywait / debian下的inotifywait 进程不销毁问题

### ISSUE THREAD

**Issue by fireyang** [falood/file_system#41]
如果把erlang的虚拟机直接halt掉，inotifywait进程不会销毁。exfswatch没有这个问题。exfswatch用sh的read来kill 进程，而file_system中直接创建了inotifywait，如果erlang的vm被kill掉，这个inotifywait的进程就没办法kill了。导致inotifywait的进程数过多问题！

**Comment by falood** [comment]
Hi @fireyang 
今天再次确认了一下，这个问题已经通过 #39 修复了，请再次确认下你使用的是最新版的代码。
如果依然有问题，希望回复如下信息，我会尽可能用和你一样的环境测试。
操作系统版本，erlang 版本，elixir 版本，并提供 mix.lock 文件

多谢。

**Comment by fireyang** [comment]
恩，应该是exsync的2.2版本没有更新依赖的原因吧，hex.pm也更新下依赖吧

**Comment by falood** [comment]
exsync v0.2.1 released 🙂 
Thanks @fireyang
