### ISSUE TITLE
fs issue on CentOS linux

### ISSUE THREAD

**Issue by smpallen99** [falood/file_system#5]
I just posted [issue 23 with fs](https://github.com/synrc/fs/issues/23) when trying to monitor a file with inotify-tools-3.14-1.el6.x86_64. Its a backend issue with `line_to_event`. Cross posting here in case anyone else experiences it. I have a temporary fix on the `linux_fix` branch on my clone.

**Comment by falood** [comment]
I tried to wait for updating from `synrc/fs` and I didn't get any response.
So I merge your `linux_fix` branch and release `v0.2.0`.
Thank you :D
