### ISSUE TITLE
Can't get file_system to compile 

### ISSUE THREAD

**Issue by mido18** [falood/file_system#57]
This happened after updating for Mojave
Mohameds-MacBook-Pro:umm mohamed$ mix deps.compile file_system
```

01:31:26.566 [info]  Compiling file system watcher for Mac...
==> file_system
c_src/mac/cli.c:1:10: fatal error: 'getopt.h' file not found
#include <getopt.h>
         ^~~~~~~~~~
1 error generated.

01:31:26.606 [error] Could not compile file system watcher for Mac, try to run "clang -framework CoreFoundation -framework CoreServices -Wno-deprecated-declarations c_src/mac/*.c -o priv/mac_listener" manually inside the dependnecy.
```

**Comment by hugrave** [comment]
I have the same issue...

**Comment by falood** [comment]
it's the same issue here, could you please check whether this works?
https://elixirforum.com/t/getopt-headers-not-found-when-building-fresh-app/3356

**Comment by bjufre** [comment]
@mido18 Did you manage to solve this?

**Comment by mido18** [comment]
@behind-design yup it was related to python_path overriding the system c libs

**Comment by fireproofsocks** [comment]
How did you solve this exactly?  I installed python anaconda recently, but I didn't think it had anything to do with my Elixir work.

**Comment by myobie** [comment]
In case you arrive here like I did, exporting `SDKROOT` does fix this issue for me and can be found in [the forum post](https://elixirforum.com/t/getopt-headers-not-found-when-building-fresh-app/3356). I cannot, however, figure out why this isn't a problem on all of my Macs. I've added `export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"` to my bash profile just in case.

**Comment by justinmorrow** [comment]
@myobie appreciate you passing along the fix! I'll update this comment if it works/doesn't for me (just haven't taken the time to recompile yet, with `SDKROOT` set)

By the way, I think you have a minor typo here
> ... exporting `SDKPATH`...
> I've added `export SDKROOT="`...

Thought I'd point it out for future readers, so they don't bother reading through the forum post to find out `SDKROOT` is the one you want (As far as I can tell: I haven't taken the time to actually understand the problem enough to be sure)

**Comment by r-guimaraes** [comment]
Still not working for Sonoma. where is this header file located now?
