### ISSUE TITLE
Incorrect directory name processing with non-ascii characters

### ISSUE THREAD

**Issue by ytsiuryn** [falood/file_system#63]
I processe some directory with cyrillic name "!А. Дворжак - Квинтет для фортепиано, двух скрипок, альта и виолончели соч 81 [A 10-00067-001] [1984]".

file_system callback returns:
```
15:34:57.358 [debug] inotify: dir .../!ÐÐ²Ð¾ÑÐ¶Ð°Ðº - Ð²Ð¸Ð½ÑÐµÑ Ð´Ð»Ñ Ñ
                                                                                         Ð¾ÑÑÐµÐ¿Ð¸Ð°Ð½Ð¾, Ð´Ð²ÑÑ
 ÑÐºÑÐ¸Ð¿Ð¾Ðº, Ð°Ð»ÑÑÐ° Ð¸ Ð²Ð¸Ð¾Ð»Ð¾Ð½ÑÐµÐ»Ð¸ ÑÐ¾Ñ 81 [A 10-00067-001] [1984] created
```
After that my directory is not found with File.ls/1.

`String.to_charlist/1` conversion is a bad suggestion, because I have error {:error, :enametoolong} with directory listing.

`:file.native_name_encoding`                                                                                                         
>> :utf8

`:io.printable_range`
>> :latin1

shell locale command output:
locale
LANG=ru_RU.UTF-8
...
LC_ALL=ru_RU.UTF-8

**Comment by falood** [comment]
Hi @gtyrin 
I tried this several locally, but I'm not able to reproduce it.
could you please show me such informations:
1. `uname -a`
2. how you create this dir

**Comment by ytsiuryn** [comment]
uname -a
Linux debian 4.19.0-8-rt-686-pae #1 SMP PREEMPT RT Debian 4.19.98-1 (2020-01-26) i686 GNU/Linux

My callback catches changes (about new dir) when a directory moves from some source directory to listened one into the same disc volume (for example, into /home). Ctrl-X/Ctrl-V in Thunar file manager.

**Comment by falood** [comment]
Hi @gtyrin 
I tried debian in a virtual machine, still not able to reproduce.
if you get the error `enametoolong`, maybe it's related to the filesystem type, like ext4, btrfs
could you try:

1. whether a longe file name in purge english work? the currently file name is 159 bytes.
2. whether a shoter Russian file name work? make a less than 8 bytes.

**Comment by ytsiuryn** [comment]
Hi @falood.
My PC's HDD partitioned with LVM and Ext4 file system.
Long file name is the smallest problem for me, because file system doesn't recognize existing file without right codepage.

**Comment by falood** [comment]
Hi @gtyrin 

It's still hard for me to produce, could you please try inotify directly?
this project is a wrapper of inotify for linux platform

**Comment by ytsiuryn** [comment]
I have found the input text encoding. That is ISO-8859-1.
The problem is solved using the code below:
`{:ok, msg} = Codepagex.from_string(path, :"ISO8859/8859-1")
`
