### ISSUE TITLE
function :inotifywait.find_executable/0 is undefined

### ISSUE THREAD

**Issue by alesasnouski** [falood/file_system#8]
Unable to start exsync application with 0.2.0 exfswatch tag, though 0.1.1 works ok. 
The following error arises:

```
** (Mix) Could not start application exfswatch: exited in: ExFSWatch.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :inotifywait.find_executable/0 is undefined (module :inotifywait is not available)
            :inotifywait.find_executable()
            (exfswatch) lib/exfswatch.ex:19: ExFSWatch.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
```

Arch linux, Elixir 1.3.2, erlang 0.18.3.

~which inotifywait
/usr/bin/inotifywait

**Comment by falood** [comment]
I checked this and found that `fs` wouldn't be downloaded by `mix deps.get` and I made an issue [here](https://github.com/hexpm/hex/issues/264).
Add `{:fs, github: "synrc/fs", tag: "1.9"}` to your dependences may resolve your problem.

**Comment by alesasnouski** [comment]
Yep. You are right!  Thank you.
