### ISSUE TITLE
Change license or dual license

### ISSUE THREAD

**Issue by hauleth** [falood/file_system#88]
IIRC WTFPL is not really binding in some jurisdictions, which mean that this software can be considered proprietary in some countries. That may be a problem there. So my proposal is to dual license it as WTFPL and 0BSD/MIT or something like that to avoid that trap.

**Comment by falood** [comment]
that's really something important, thanks for pointing it out.
but I saw elixir is using apache https://github.com/elixir-lang/elixir/blob/main/LICENSE
any suggestion between apache and BSD/MIT?

**Comment by hauleth** [comment]
Apache has also patent clausule. Honestly - whatever works for you, no strong feelings. I pointed out these two licenses as these are closest one to WTFPL in their core.
